import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-skin-base">lol</h1>
        <h1 className="text-skin-inverted">letsgo</h1>
        <div className="w-10 h-10 rounded-lg bg-skin-inverted text-skin-inverted">
          yo
        </div>
        <div className="w-10 h-10 flex justify-center items-center bg-accent-base">
          yo
        </div>
        <div className="w-10 h-10 flex justify-center items-center bg-accent-muted">
          yo
        </div>
        <div className="w-10 h-10 flex justify-center items-center bg-accent-inverted">
          yo
        </div>
      </main>
    </>
  );
}
